### ISSUE TITLE
Web Panel Accessibility

### ISSUE THREAD

**Issue by daronhudson** [cookkkie/mee6#104]
So I've gotten the Bot and website to run just fine, but the website seems to only be accessible via localhost and it's running on a linux server.. I've been tinkering with settings all day and I can't seem to get it to bind to anything but 127.0.0.1. Any Ideas?

**Comment by MrRedAmber** [comment]
Are you running it with docker or?

**Comment by SilBoydens** [comment]
if you just clone this repo then you have the dev version of the bot, wich only works on localhost.
disable all debugers to use it on other urls too

**Comment by daronhudson** [comment]
Nevermind I figured it out!
