### ISSUE TITLE
Manage Server Permissions, why?

### ISSUE THREAD

**Issue by KSib** [cookkkie/mee6#118]
Is there a reason Mee6 bot requires these permissions now? I only like to give it the permissions it needs. It shouldn't need to change the server's name or have the server change regions.

Thanks!

![image](https://user-images.githubusercontent.com/1589238/28242812-a9f1468c-697b-11e7-86d7-4f893d59a0a5.png)

**Comment by SilBoydens** [comment]
that means that YOU need manage server permision to add Mee6 to your server, Mee6 does not need that permission and you can uncheck it

**Comment by KSib** [comment]
Gotcha. I think the site being down (still down as of this message) confused me. I tried to add it without the permission and the same page just came back up so I thought it needed to have that permission.

**Comment by SilBoydens** [comment]
no, it keeps giving that page because it is unable to get the needed info from discord (aka channels and roles list) because the bot is currently offline, try again in a hour or so

**Comment by KSib** [comment]
Sounds good. I'll try later.
