### ISSUE TITLE
[Suggestion] Allow Score/Rank Editing .

### ISSUE THREAD

**Issue by Imseriouslypro** [cookkkie/mee6#122]
Allowing Addition of scores for leaderboards, Since I have seen Rouge Moderators get Abusive and "Reset" People for no reason .
Adding something like -
-
!score Add @User [Amount]
!score remove @User [Amount]
!score set @User [Amount]
-
(Or directly editing /adding a rank level)
-
This would Come in use where someone got thier leaderboard Rank reset by mistake or for wrong reason. Some bots I have seen e.g. Tatsumaki already do this .

**Comment by cookkkie** [comment]
I'm planning on adding that but before that I have to add a log feed where anyone can see these types of actions (xp given, resets & co) and who did what.
