### ISSUE TITLE
Manage XP per level/role?

### ISSUE THREAD

**Issue by GonthorianDX** [cookkkie/mee6#123]
Hi,

I stumbled upon your bot and I am very happy with it so far, my only concern is that I have no way to control how much XP I need for a certain level/role for my guests, is this something I missed or is this not 
 (yet) implemented in the bot?

Thank you.

**Comment by SilBoydens** [comment]
it follows a simple formula  
`5 * (lvl ^ 2) + 50 * lvl + 100` with lvl being your current level and the result of this formula being the xp needed for the next level.
making this diffrent for diffrent servers is to much of a hastle and to much calculating to do so, no you won't be able to change it

http://mee6.github.io/Mee6-documentation/levelxp/

**Comment by GonthorianDX** [comment]
Thank you for your reply,

Another issue I found is that Mee6 does not make use of my own emoji's, I got my :{Emoji}: but Mee6 only gives it in text format, is this a bug or am I doing something wrong?

**Comment by SilBoydens** [comment]
custom emojies in discord are in the form of `<:name:NUMERIC_ID>`
to get the right from try doing \\:emojiname: in your server and send that message
then copy that whole thing and paste it in a Mee6 message

for faster respondses, try Mee6 support server at http://discord.gg/mee6
