### ISSUE TITLE
Twitch Announcements are super slow and sporadic

### ISSUE THREAD

**Issue by Polar05** [cookkkie/mee6#124]
The Twitch integration is super slow to announce a stream has gone live (up to 15 minutes), if it even announces it at all. Sometimes it will even double announce for unknown reasons.

**Comment by SilBoydens** [comment]
double annoucements => streamers had a short stream right before the real stream (can happen when changing stream title, check there vids on twitch for proof)

delay => twich limits the amount of streamers Mee6 can check in a certain time period 

for any question regarding Mee6 the bot hosted by us (and not about the code) pls ask in the Mee6 support server http://discord.gg/mee6
