### ISSUE TITLE
Two Underscores Lining up to Slant Letters

### ISSUE THREAD

**Issue by P0isonn** [cookkkie/mee6#127]
http://prntscr.com/gbeyk6

There is supposed to be an underscore between the P and N in Crisp_P_Nuggets and there is supposed to be an underscore after the z in JacksonPlayz_. Discord, however, is finding these two underscores and slanting whatever is between them. Is there anyway to fix this?

**Comment by KamikazePotato** [comment]
Put a ` on both sides of {streamer} so its like `{streamer`. This fixes it

**Comment by DeathByKorea** [comment]
You can also escape it by adding a \ before it
