### ISSUE TITLE
[Question] Self-Hosting Port

### ISSUE THREAD

**Issue by jKemmkey** [cookkkie/mee6#129]
Hello. Just hosted a version of the bot on a personal machine. Is there any way to change the default port from 5000 to another one?

Greetings

**Comment by SilBoydens** [comment]
Mee6 website uses flask, so this should help you:
https://stackoverflow.com/questions/41940663/why-cant-i-change-the-host-and-port-that-my-flask-app-runs-on
http://flask.pocoo.org/docs/0.12/api/

**Comment by jKemmkey** [comment]
Ty
