### ISSUE TITLE
take two strokes off my golf game!

### ISSUE THREAD

**Issue by EtienneDemers** [cookkkie/mee6#139]
So this mee6 bot is nice and co0l and stuff...

BUT

i see no way to ask the mee6 to take two strokes off my golf game!

It would be more-than-awesome to have a feature to ask the mee6 to take two strokes off a golf game and see it turn into a self-loathing-death-wishing-self-multiplicating-murder-psycho in the chat room.

Consider this a feature request.

**Comment by cookkkie** [comment]
![It'd be savage!](https://media.giphy.com/media/1UrLooZOVeGly/giphy.gif)
