### ISSUE TITLE
Privacy issues with online public stats 

### ISSUE THREAD

**Issue by Magissia** [cookkkie/mee6#142]
It should be possible for people to not be listed in online public "leaderboard" as it can be used for stalking, there are no obvious way for an user to opt out of this.

The stats page online require channel ID without any form of authentication.

Opting out should not require anything more than using a command from the account to opt out in a channel where the bot is connected or a direct message. All previous data linked to the user of it exist should be removed from server, only the strict minimum required to keep the opt out working should be kept, like the hash of the account ID.

**Comment by cookkkie** [comment]
#137
