### ISSUE TITLE
Timer broken?

### ISSUE THREAD

**Issue by AshenDragonAzoth** [cookkkie/mee6#157]
I'm in a discord server for For Honor (all 12 of us that still play), and we were using Mee6 to remind us when the war map in game changes. This happens every 11 hours, and initially, Mee6 would be on time, but slowly drift off. Recently, he's been off by many hours, and was pinging us every two hours the last day or two. What's causing these errors, and can they be fixed?

**Comment by cookkkie** [comment]
Hi, please join use in https://discord.gg/mee6 and DM me personally so that we can communicate much more easily.
