### ISSUE TITLE
[Minor] Three Underscores Omitted in Twitch Username

### ISSUE THREAD

**Issue by Dreadth** [cookkkie/mee6#158]
When a username is posted with three underscores in Twitch, the underscores get omitted from the link causing the link to go to the wrong location. Also, anything after the three underscores will not be linked.

**Example:**
[twitch.tv/test___user](url) becomes [twitch.tv/test](url)user
(No idea if these are actual twitch accounts)

**Comment by Woody5728** [comment]
This is because of the Discord Markdown system where _ is used to make text italics. In the announcement message do `{streamer}` and/or <{link}> to avoid the omitted underscore

**Comment by Dreadth** [comment]
The only markup I had any luck with was using the asterisk to enclose the underscores... I couldn't make anything else work. So my final format is as follows:

Hey @everyone! *{streamer}* is now live on **{link}** ! Go check it out 😉!
