### ISSUE TITLE
Is there an API for update points

### ISSUE THREAD

**Issue by Jaom** [cookkkie/mee6#161]
I'd need to use a third party bot to update values of reputation for a specific user. Is there a way to do it?

**Comment by SilBoydens** [comment]
There is a API comming soon, but what do you mean with reputation

**Comment by Jaom** [comment]
Exp :)

**Comment by SilBoydens** [comment]
NO!! You will never be able to give xp, the API will alloy you to get someone his xp or to reset someone

**Comment by Jaom** [comment]
Ok, thanks
