### ISSUE TITLE
Inefficient interop with ytdl-core (voice bot)

### ISSUE THREAD

**Issue by qeled** [cookkkie/mee6#4]
Current implementation can be improved by not using built-in proxy stream from `ytdl-core` but instead passing the url to ffmpeg directly:
- this eliminates the need for stdin piping,
- stops the `ECONNRESET` errors from happening (which I believe is a bug in the `ytdl-core` caused by data proxying with `PassThrough` stream),
- allows seeking over the stream,
- and makes the process more efficient.

You can find a ytdl example in the [documentation](https://qeled.github.io/discordie/#/docs/FFmpegEncoder) now: https://qeled.github.io/discordie/#/docs/FFmpegEncoder

```js
function playRemote(remote, info) {
  function onMediaInfo(err, mediaInfo) {
    if (err) return console.log("ytdl error:", err);
    // sort by bitrate, high to low; prefer webm over anything else
    var formats = mediaInfo.formats.filter(f => f.container === "webm")
    .sort((a, b) => b.audioBitrate - a.audioBitrate);

    // get first audio-only format or fallback to non-dash video
    var bestaudio = formats.find(f => f.audioBitrate > 0 && !f.bitrate) ||
                    formats.find(f => f.audioBitrate > 0);
    if (!bestaudio) return console.log("[playRemote] No valid formats");

    if (!info) info = client.VoiceConnections[0];
    if (!info) return console.log("[play] Voice not connected");
    var encoder = info.voiceConnection.createExternalEncoder({
      type: "ffmpeg", source: bestaudio.url
    });
    encoder.play();
  }
  try {
    ytdl.getInfo(remote, onMediaInfo);
  } catch (e) { console.log("ytdl threw:", e); }
}
```

Also worth noting that ffmpeg can't transcode `mp4` in seekable mode over HTTP until fully downloaded (enabled by default, you can turn it off with `-seekable 0`), thus this example only uses `webm` (which also almost always offers better quality).

There's also an option for playing opus audio without ffmpeg - take a look at [`WebmOpusPlayer`](https://qeled.github.io/discordie/#/docs/WebmOpusPlayer).

**Comment by cookkkie** [comment]
Thanks :smile: . In term of performance, what's the best iyo? using ffmpeg or the WebmOpusPlayer?

**Comment by qeled** [comment]
Since `webm` can contain vorbis-encoded audio, use ffmpeg to transcode it as you do now, otherwise you can just play opus with `WebmOpusPlayer`. You can detect encoding by inspecting `audioEncoding` property in the formats.

**Comment by cookkkie** [comment]
Thanks :+1: . I'll do that. Curious to see if it's worth it to use `WebmOpusPlayer`. I mean, how many videos have an opus `audioEncoding` on youtube.

**Comment by cookkkie** [comment]
So, it's working fine. But my docker container is freakin out... Got `FFmpegEncoder: external encoder exited with code 1`. But I'm feeling I installed ffmpeg correctly. I have installed that with `libopus` and `libvordis`. Since webm does only support that audio right?

**Comment by qeled** [comment]
How did you install it into the container? I think you need all the libraries the ffmpeg binary is linked to in the container for it to work properly, not only `libopus` and `libvorbis`.

**Comment by cookkkie** [comment]
https://gist.github.com/33920d498f99ac863aeb42e158230c1a
Here it is @qeled

**Comment by cookkkie** [comment]
sshing into the container and executing `ffmpeg` works good

**Comment by qeled** [comment]
I don't really see HTTPS support in there, maybe it doesn't support the protocol. I think installing `openssl` and `libssl-dev` and compiling with `--with-openssl` flag should do it.

**Comment by cookkkie** [comment]
Partial fix here https://github.com/cookkkie/mee6/commit/198776663a6ff52ca5ea3234e84df5a60f8d890f
