### ISSUE TITLE
[REQUEST] Auto Playlist feature

### ISSUE THREAD

**Issue by Circuitree** [cookkkie/mee6#42]
Would like to request an Auto Playlist for the Music feature. Like add a field that you can type so many (2-300) Youtube/SoundCloud song links (https://www.youtube.com/watch?v=blahblahblah), kind of like Sexual Rhinoceros Discord Bot.

**Comment by SilBoydens** [comment]
planned, kind of.

the current plan is to have 2 modes:
-a request mode(the current one)
-a radio mode, you will be able to create a playlist on the Mee6 dashbaord and when no songs are requested anymore and the request playlist is empty it would automaticly switch to the radio mode
(this is planned to add and not implemented yet, pls wait for updates)

ps. close this issues

~Sil : Mee6 support team
official support discord server: https://discord.gg/0tOgeGSG9kYFepgL
