### ISSUE TITLE
Please make the level up stuff opt-in

### ISSUE THREAD

**Issue by KazeSenoue** [cookkkie/mee6#48]
Nobody likes getting pinged and DM'd constantly about this shit.

**Comment by SilBoydens** [comment]
you can disable it 
![image](https://cloud.githubusercontent.com/assets/9578499/17648223/a00e018a-620d-11e6-82b2-fdb279195674.png)
uncheck the checkbox enable/disable to not get messages or PM about level up.
this is a server setting and can only be disable by the server owner or a admin on that server.
(http://mee6.xyz/servers => select your server => level plugin in the left)

~Sil - Mee6 support team
Mee6 support server: https://discord.gg/0tOgeGSG9kV0jasj

**Comment by KazeSenoue** [comment]
This makes absolutely no sense. Getting PMd by things nobody cares about should be an opt-in feature *per user*, not opt-out per server. This is a fatal flaw on your bot's design, and it's the reason multiple people have it blocked.

**Comment by KazeSenoue** [comment]
14 days until this issue's 6 month birthday and still no answer.

**Comment by SilBoydens** [comment]
it is  a server __opt-in__, i would not even know how to make it user opt-in or opt-out.

the default is that he says you leveled up in the channel where you leveled up, but with a __opt-in__ option to let it send in DM

**Comment by KazeSenoue** [comment]
I didn't opt-in to this. http://i.imgur.com/oCbka4U.png

**Comment by SilBoydens** [comment]
ask a server admin to either put in it in the server or completly disable it if you really don't want it

**Comment by KazeSenoue** [comment]
Or fix your bot so I don't need to ask server owners to do it for you. I used to have it blocked for the longest time but one of the streamers I follow uses it for stream alerts, so sadly I have to keep dealing with useless, unrequested DMs.

**Comment by KazeSenoue** [comment]
Because that's easier than fixing your bot, right?

2017-04-01 12:15 GMT-03:00 Sil Boydens <notifications@github.com>:

**Comment by KamikazePotato** [comment]
That poor attitude isn't going to get you far

**Comment by KazeSenoue** [comment]
Good thing I came here to report an issue on this particular piece of
software, not get educated.

2017-04-02 0:59 GMT-03:00 KamikazePotato <notifications@github.com>:

**Comment by Cazzar** [comment]
I agree with adding the option to have the levelling disabled on a global *per user* basis, because it is quite often that I would believe the bot gets muted whenever this starts occuring.

I can see people enjoying it, so no harm in getting that done, but do you see many other things akin to idlerpg/chat levelling DMing you as soon as an event occurs?

**Comment by MrRedAmber** [comment]
@KazeSenoue If you're going to be belligerent, no one is going to help you. Don't be part of the the problem, be part of the solution.

**Comment by KazeSenoue** [comment]
@MrRedAmber I took my own free time to help this project, reporting a critical issue in functionality, and what I got was 7 months of silence. If the solution is being completely oblivious to disrespect, then I'm glad to not be part of it. Also, no one is going to take you seriously if you're acting so condescending.

**Comment by MrRedAmber** [comment]
@KazeSenoue We appreciate you taking your time to help. Please understand that there are only a handful of developers that contribute to this repository and that you're issue isn't critical.

**Comment by KazeSenoue** [comment]
So you're fine with not fixing the fact that your bot creates unnecessary noise, causing many people to outright block it. Not my problem I guess. Best wishes.

**Comment by KamikazePotato** [comment]
just get a banned role, dont level, and no level up message. problem solved

**Comment by AraHaan** [comment]
I do admit that sometimes the server owner is buisy and that nobody is there to disable it for an particualr person. I guess the bot needs a command to ignore leveling stuff globally. I will see what I can do to add one.

**Comment by KazeSenoue** [comment]
@KamikazePotato Hilarious.

@AraHaan Yes, exactly. Making it opt-in is a bit overkill, but at the very least we should be able to globally opt out of it, meaning we won't get bothered by it in every server the bot is in. I honestly wouldn't mind doing it myself, but I've been busy with work.

**Comment by AraHaan** [comment]
@KazeSenoue what you think on how I did it? I could make another command for them to opt in in case they change their mind at a later time on it.

**Comment by KazeSenoue** [comment]
@AraHaan It's perfect. An opt-in command is probably a good idea as well.

**Comment by AraHaan** [comment]
Alright I added it as well.
