### ISSUE TITLE
Beam streams show up as twitch.tv on notification

### ISSUE THREAD

**Issue by kluge-iitk** [cookkkie/mee6#50]
Beam.pro streams that are tracked by mee6 show up as twitch.tv/channel_name instead of beam.pro/channel_name when the beam stream goes live.

**Comment by SilBoydens** [comment]
![image](https://cloud.githubusercontent.com/assets/9578499/18032757/9ec6c664-6d10-11e6-88b4-6bd9bf44be33.png)
this should explain what is wrong, 
on http://mee6.xyz/servers , select your server, twitch and co plugin, change the twitch link to `{link}` then it will be correct

**Comment by kluge-iitk** [comment]
Yeah that should do it. Thanks! I think the default announcement message should be using `{link}` instead of `twitch.tv/{streamer}`
