### ISSUE TITLE
Slowmode

### ISSUE THREAD

**Issue by FISHunderscore** [cookkkie/mee6#57]
What exactly does slowmode do? It does not seem to delete excess messages sent by a single user, so...

**Comment by SilBoydens** [comment]
slowmode is a way to combat spam, Mee6 will delete message of users who spam to much.
when you enable slowmode then Mee6 will delete all message that are less then xx seconds behind the previous message of that member.
use `!slowmode xx` to activate it(with xx being the time in seconds between 2 messages of the same users).
use `!slowoff` to disable it.
```diff
+ Mee6 need manage messages permission
+ you need a role that is set as modurator role on the bottem of the modurator plugin page
- members with a role set as modurator role will not be efected by slowmode
```

~Sil from Mee6 support team
Mee6 support server: https://discord.gg/0tOgeGSG9kYFepgL

**Comment by FISHunderscore** [comment]
Thanks. I didn't know that mods were immune.
