### ISSUE TITLE
Bot not removing messages

### ISSUE THREAD

**Issue by DocPoke** [cookkkie/mee6#62]
the bot doesn't remove messages but only says deleted -1 messages.
![image](https://cloud.githubusercontent.com/assets/19578675/20058338/2350ca18-a4f9-11e6-8e51-5674ea022784.png)

**Comment by SilBoydens** [comment]
this means that he does not have the 'read message history' permission, if he can't see the old messages then he can't delete them

~Sil from Mee6 support team
Mee6 support server with faster respondstime: https://discord.gg/0tOgeGSG9kV0jasj

**Comment by DocPoke** [comment]
thank you :)
