### ISSUE TITLE
Username in custom commands

### ISSUE THREAD

**Issue by jtvjan** [cookkkie/mee6#64]
For example, if the !custom command is:
`{username} is awesome.`
It would be used like this:
```
<Rick> !custom
<Mee6> Rick is awesome.
<Morty> !custom
<Mee6> Morty is awesome.
```

**Comment by treetrnk** [comment]
You can kind of do this already, though not exactly as you requested. If you use `{user}` in the response with will replace it with a mention to your user. So instead of what you suggested the output would be: 

```
<Rick> !custom
<Mee6> @Rick is awesome.
<Morty> !custom
<Mee6> @Morty is awesome.
```
