### ISSUE TITLE
Add ignore channel possibility

### ISSUE THREAD

**Issue by sammyvsparks** [cookkkie/mee6#8]
As i see, you can't have mee6bot ignore channels for cursing or other moderation actions at this time and that would be a neat feature to see.

**Comment by SilBoydens** [comment]
don't give Mee6 acces to the channels you wnat him to ignore
(give the rank that the bot has no acces to those channels)

**Comment by RBGaming** [comment]
i want mee6 to ignore the !level command in my main text chat
