### ISSUE TITLE
Twitch Stream Notifications

### ISSUE THREAD

**Issue by ToxicYTT** [cookkkie/mee6#81]
i enabled the twitch streaming  notifications and entered my tag on twitch but when i go live the notification doesnt pop up for anyone in my discord. evryone else entered will pop up a notification though. is there a way to fix this?

**Comment by cookkkie** [comment]
Could you give mee6 attachements posting permission and try again please?

**Comment by ToxicYTT** [comment]
I have that already. I have a friend and I on the stream notifications and his notifications pop up but not mine

**Comment by ToxicYTT** [comment]
@cokkkie

**Comment by ToxicYTT** [comment]
I didn't put in my tag wrong or anything so I don't know what's wrong

**Comment by ToxicYTT** [comment]
@cookkkie

**Comment by SilBoydens** [comment]
@ToxicYTT can you remove your name from the list and **TYPE** it in pls, sometimes when doing a copy-paste you have charaters in it that should not be there.

**Comment by ToxicYTT** [comment]
OK I got it we are good I did what sil  boydens told me to do
