### ISSUE TITLE
My Discord Account was banned for stating a bug

### ISSUE THREAD

**Issue by BourKeeg815** [cookkkie/mee6#98]
Hello,

I was banned from the Mee6 Discord server after I reported a bug! They said when they banned me that it was because I was inviting people to my server through DM (The reason being that I said "I found a bug and there was a problem on my server, can you join to see why")

I hope we can fix this, if you need my discord name, can you email keegan@kryo.pro

I hope we can get this fixed!
Thanks!

**Comment by SilBoydens** [comment]
what is your discord name?
@BourKeeg815

**Comment by BourKeeg815** [comment]
Its Keegan#7010

**Comment by SilBoydens** [comment]
done, http://discord.gg/mee6 (can you close this issue?)
